{
   ####search result diversification model settings
   model: "llm",

   log_name: "ClueWeb09-DESA",
   model_save_dir: "model/",
   tmp_dir: "tmp/",
   doc_content_dir: "clueweb09_doc_content_dir/",

   reprocess: False,

   mode: "train",
   best_model_list: [],

   device: "cpu",
   epoch: 3,
   batch_size: 8,
   learning_rate: 0.01,
   dropout: 0,

   eval_steps: 10,

   embedding_type: "doc2vec",
   embedding_length: 100,

   api_url: "",
   api_key: "",
}