{
   ####search result diversification model settings
   model: "DALETOR",

   log_name: "ClueWeb09-DESA",
   model_save_dir: "model/",
   tmp_dir: "tmp/",

   reprocess: False,

   mode: "train",
   best_model_list: [],

   device: "cpu",
   epoch: 3,
   batch_size: 8,
   learning_rate: 0.01,
   dropout: 0,

   eval_steps: 10,

   embedding_type: "doc2vec",
   embedding_length: 100,
}