group_aggregation_threshold: 10
group_id: publisher:token
group_num: 43
group_val: 5
history_field: history_behaviors
history_length: 5
item_id: product_id:token
item_num: 1238
item_val: 5
label_id: label:float
label_threshold: 10
reprocess: true
sample_num: 200
sample_size: 1.0
test_ratio: 0.1
text_id: title:token
timestamp: timestamp:float
user_id: user_id:token
user_num: 4446
user_val: 5
valid_ratio: 0.1
