{
   model: mf,
   device: cpu,
   epoch: 20,
   batch_size: 32,
   learning_rate: 0.001,
   log_name: "base_mf",
   eval_step: 5,
   eval_type: 'ranking',
   watch_metric: 'ndcg@5',
   store_scores: True,
}