{
   model: gru4rec,
   data_type: 'sequential', #[point, pair, sequential]

#   model: gru4rec,
#   data_type: 'sequential', #[point, pair, sequential]

   ####fair-rank model settings
   fair-rank: True, ##if you want to run a fair-rank module on the base models, you should set the value as True
   rank_model: 'APR',


   log_name: "steam-APR-base_mf",
   mmf_eval_ratio: 0.5,
   decimals: 4,

   device: cpu,
   epoch: 20,
   batch_size: 32,
   learning_rate: 0.001,

   eval_step: 10,
   eval_type: 'ranking',
   watch_metric: 'mmf@20',

   topk: [ 5,10,20 ], # if you choose the ranking settings, you can choose your top-k list
   store_scores: True,
}