{
   model: "FairSync",
   log_name: "FairSync-steam-mf",
   topk: [5, 10, 20],
   fairness_metrics: ['EF', "MMF", "GINI", "Entropy"],
   fairness_type: "Utility", # ["Exposure", "Utility"], where Exposure only computes the exposure of item group while utility computes the ranking score of item groups
   ranking_store_path: "2024-11-8_base_mf", ##the ranking score stored path for the re-ranking, only re-ranking should change the value
   #ranking_store_path: "2025-1-2_Amazon_Digital_Music-base_mf",
   #ranking_store_path: "2025-1-2_yelp-base_mf",
}